/**
 * Sri Lakshmi Jewellers - Product Catalog Database
 * High-end lightweight and 1-gram gold jewellery with dual photography (primary + hover)
 */

const PRODUCTS = [
    {
        id: "SLJ001",
        name: "Lakshmi Temple Kasu Haram",
        category: "Harams",
        style: "Temple",
        occasion: "Wedding",
        collection: "Bridal",
        price: 4999,
        originalPrice: 6299,
        image: "images/products/slj001.jpg",
        hoverImage: "images/products/slj001_hover.jpg",
        gallery: [
            "images/products/slj001.jpg",
            "images/products/slj001_hover.jpg",
            "images/products/slj001_detail.jpg"
        ],
        description: "Intricately handcrafted grand Kasumala featuring Goddess Lakshmi stamped motifs with ruby red kemp doublet stones, finished in authentic 1-gram matte micro-gold plating.",
        finish: "1-Gram Micro Gold Matte Polish",
        material: "High-grade Brass & Copper Alloy with Kemp Stones",
        weight: "58 grams approx.",
        size: "Adjustable dori length 24 to 28 inches",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 4.9,
        reviewsCount: 42
    },
    {
        id: "SLJ002",
        name: "Peacock Floral Heritage Choker",
        category: "Necklaces",
        style: "Antique",
        occasion: "Bridal",
        collection: "Bridal",
        price: 3899,
        originalPrice: 4899,
        image: "images/products/slj002.jpg",
        hoverImage: "images/products/slj002_hover.jpg",
        gallery: [
            "images/products/slj002.jpg",
            "images/products/slj002_hover.jpg",
            "images/products/slj002_detail.jpg"
        ],
        description: "Regal peacock carved antique choker necklace with cluster pearl hangings and matching statement jhumkas for bridal celebrations.",
        finish: "Antique 22k Gold Glow Plating",
        material: "Copper Alloy with South Sea Faux Pearls & Kundan",
        weight: "44 grams approx.",
        size: "Adjustable back rope choker",
        featured: true,
        newArrival: false,
        trending: true,
        rating: 4.8,
        reviewsCount: 36
    },
    {
        id: "SLJ003",
        name: "Chandbali Royal Heritage Jhumkas",
        category: "Jhumkas",
        style: "Temple",
        occasion: "Festive",
        collection: "Signature",
        price: 1899,
        originalPrice: 2499,
        image: "images/products/slj003.jpg",
        hoverImage: "images/products/slj003_hover.jpg",
        gallery: [
            "images/products/slj003.jpg",
            "images/products/slj003_hover.jpg",
            "images/products/slj003_detail.jpg"
        ],
        description: "Traditional dome-shaped jhumkas adorned with ornate crescent chandbali tops and dangling pearl seed clusters.",
        finish: "Premium Matte Gold Finish",
        material: "Brass Core with CZ Stones and Hydro Emerald beads",
        weight: "22 grams per pair",
        size: "Length: 2.8 inches",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 5.0,
        reviewsCount: 48
    },
    {
        id: "SLJ004",
        name: "Mayura Kemp Ruby Kada Bangles (Pair)",
        category: "Bangles",
        style: "Traditional",
        occasion: "Festive",
        collection: "Signature",
        price: 2299,
        originalPrice: 2899,
        image: "images/products/slj004.jpg",
        hoverImage: "images/products/slj004_hover.jpg",
        gallery: [
            "images/products/slj004.jpg",
            "images/products/slj004_hover.jpg",
            "images/products/slj004_detail.jpg"
        ],
        description: "Openable screw-type peacock embossed Kada bangles encrusted with hand-set kemp rubies and subtle emerald accents.",
        finish: "1-Gram Micron Gold Dip",
        material: "Brass Base with Hand-faceted Kemp Stones",
        weight: "36 grams (Pair)",
        size: "Available: 2.4, 2.6, 2.8 with screw lock",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 4.7,
        reviewsCount: 29
    },
    {
        id: "SLJ005",
        name: "Contemporary Solitaire Floral Ring",
        category: "Rings",
        style: "Contemporary",
        occasion: "Daily",
        collection: "New Arrivals",
        price: 899,
        originalPrice: 1199,
        image: "images/products/slj005.jpg",
        hoverImage: "images/products/slj005_hover.jpg",
        gallery: [
            "images/products/slj005.jpg",
            "images/products/slj005_hover.jpg",
            "images/products/slj005_detail.jpg"
        ],
        description: "Minimalist floral center design studded with Swiss-cut zirconia gemstones, featherlight for daily office or college wear.",
        finish: "Glossy Champagne Gold Tone",
        material: "Anti-tarnish Lightweight Alloy & Cubic Zirconia",
        weight: "4.5 grams",
        size: "Free size adjustable band",
        featured: false,
        newArrival: true,
        trending: true,
        rating: 4.9,
        reviewsCount: 54
    },
    {
        id: "SLJ006",
        name: "Guttapusalu Grand Bridal Set",
        category: "Bridal Sets",
        style: "Traditional",
        occasion: "Bridal",
        collection: "Bridal",
        price: 6499,
        originalPrice: 8499,
        image: "images/products/slj006.jpg",
        hoverImage: "images/products/slj006_hover.jpg",
        gallery: [
            "images/products/slj006.jpg",
            "images/products/slj006_hover.jpg",
            "images/products/slj006_detail.jpg"
        ],
        description: "Heritage Guttapusalu celebration set with rich bunches of fine natural pearl clusters, carved ruby centerpieces, and matching maang tikka & earrings.",
        finish: "High-grade 24k Micro Gold Polish",
        material: "Copper Base with Rice Pearls and Synthetic Rubies",
        weight: "86 grams complete set",
        size: "Necklace + Haram + Earrings + Maang Tikka",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 5.0,
        reviewsCount: 67
    },
    {
        id: "SLJ007",
        name: "Sleek Daily Wear Mangalsutra Chain",
        category: "Chains",
        style: "Modern",
        occasion: "Daily",
        collection: "Signature",
        price: 1299,
        originalPrice: 1699,
        image: "images/products/slj007.jpg",
        hoverImage: "images/products/slj007_hover.jpg",
        gallery: [
            "images/products/slj007.jpg",
            "images/products/slj007_hover.jpg",
            "images/products/slj007_detail.jpg"
        ],
        description: "Modern single-line black bead chain featuring dual leaf diamond-look cz pendant in 18k yellow gold polish.",
        finish: "Durable Everyday Micro Plating",
        material: "Black Onyx Beads with Micro-pave CZ",
        weight: "7.2 grams",
        size: "Length: 18 inches",
        featured: false,
        newArrival: false,
        trending: true,
        rating: 4.8,
        reviewsCount: 38
    },
    {
        id: "SLJ008",
        name: "Padmavathi Lotus Pendant with Chain",
        category: "Pendants",
        style: "Temple",
        occasion: "Festive",
        collection: "Signature",
        price: 1499,
        originalPrice: 1899,
        image: "images/products/slj008.jpg",
        hoverImage: "images/products/slj008_hover.jpg",
        gallery: [
            "images/products/slj008.jpg",
            "images/products/slj008_hover.jpg",
            "images/products/slj008_detail.jpg"
        ],
        description: "Divine blooming lotus pendant embossed with Goddess Padmavathi, paired with delicate wheat chain.",
        finish: "Antique Temple Polish",
        material: "Brass with Emerald green accent drops",
        weight: "14 grams",
        size: "Pendant: 2.2 inches, Chain: 20 inches",
        featured: false,
        newArrival: false,
        trending: true,
        rating: 4.7,
        reviewsCount: 25
    },
    {
        id: "SLJ009",
        name: "Vaddanam South Indian Bridal Waist Belt",
        category: "Vaddanam",
        style: "Temple",
        occasion: "Wedding",
        collection: "Bridal",
        price: 5499,
        originalPrice: 6999,
        image: "images/products/slj009.jpg",
        hoverImage: "images/products/slj009_hover.jpg",
        gallery: [
            "images/products/slj009.jpg",
            "images/products/slj009_hover.jpg",
            "images/products/slj009_detail.jpg"
        ],
        description: "Opulent bridal Oddiyanam/Vaddanam with Lakshmi Devi centerpiece, peacocks and dangling pearl ghungroos.",
        finish: "Royal Matte Gold",
        material: "Flexible Brass Segmented Plates with Ruby Kemp",
        weight: "95 grams",
        size: "Adjustable 26 to 38 waist",
        featured: true,
        newArrival: true,
        trending: false,
        rating: 4.9,
        reviewsCount: 22
    },
    {
        id: "SLJ010",
        name: "Vintage Filigree CZ Stud Earrings",
        category: "Earrings",
        style: "Modern",
        occasion: "Daily",
        collection: "New Arrivals",
        price: 799,
        originalPrice: 999,
        image: "images/products/slj010.jpg",
        hoverImage: "images/products/slj010_hover.jpg",
        gallery: [
            "images/products/slj010.jpg",
            "images/products/slj010_hover.jpg",
            "images/products/slj010_detail.jpg"
        ],
        description: "Delicate round studs with micro-filigree floral petals centered by brilliant faceted CZ stone.",
        finish: "Lightweight High Shine Gold",
        material: "Skin-friendly Hypoallergenic Alloy",
        weight: "3.2 grams pair",
        size: "Diameter: 1.2 cm (Push back)",
        featured: false,
        newArrival: true,
        trending: true,
        rating: 4.6,
        reviewsCount: 31
    },
    {
        id: "SLJ011",
        name: "Navaratna Royal Heritage Short Necklace",
        category: "Necklaces",
        style: "Antique",
        occasion: "Festive",
        collection: "Signature",
        price: 3299,
        originalPrice: 4199,
        image: "images/products/slj011.jpg",
        hoverImage: "images/products/slj011_hover.jpg",
        gallery: [
            "images/products/slj011.jpg",
            "images/products/slj011_hover.jpg",
            "images/products/slj011_detail.jpg"
        ],
        description: "Sacred nine gemstone (Navaratna) configuration encased in antique finished gold settings with pearl fringe.",
        finish: "Heritage Dull Gold Antique Polish",
        material: "Copper Alloy with 9 Color Astrological Stones",
        weight: "38 grams",
        size: "Length: 16 inches with extendable chain",
        featured: true,
        newArrival: false,
        trending: false,
        rating: 4.9,
        reviewsCount: 35
    },
    {
        id: "SLJ012",
        name: "Manga Malai Mango Motif Long Haram",
        category: "Harams",
        style: "Traditional",
        occasion: "Wedding",
        collection: "Bridal",
        price: 5299,
        originalPrice: 6699,
        image: "images/products/slj012.jpg",
        hoverImage: "images/products/slj012_hover.jpg",
        gallery: [
            "images/products/slj012.jpg",
            "images/products/slj012_hover.jpg",
            "images/products/slj012_detail.jpg"
        ],
        description: "Classic South Indian paisley/mango leaf sequence embellished with cabochon rubies and emerald center drops.",
        finish: "22k Micro Plated Glow",
        material: "Solid Brass Casting with Kemp Stones",
        weight: "62 grams",
        size: "Length: 26 inches",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 5.0,
        reviewsCount: 58
    },
    {
        id: "SLJ013",
        name: "Kundan Meenakari Statement Choker",
        category: "Chokers",
        style: "Contemporary",
        occasion: "Party",
        collection: "Trending",
        price: 3499,
        originalPrice: 4499,
        image: "images/products/slj013.jpg",
        hoverImage: "images/products/slj013_hover.jpg",
        gallery: [
            "images/products/slj013.jpg",
            "images/products/slj013_hover.jpg",
            "images/products/slj013_detail.jpg"
        ],
        description: "Royal uncut Kundan stones with hand-enameled pastel green Meenakari work on reverse and mint bead drops.",
        finish: "Yellow Gold Gloss Finish",
        material: "Handcrafted Foil Polki Kundan with Enameling",
        weight: "48 grams",
        size: "Adjustable dori choker",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 4.8,
        reviewsCount: 28
    },
    {
        id: "SLJ014",
        name: "Layered Pearl & Gold Beads Mala",
        category: "Chains",
        style: "Lightweight",
        occasion: "Daily",
        collection: "Signature",
        price: 1199,
        originalPrice: 1599,
        image: "images/products/slj014.jpg",
        hoverImage: "images/products/slj014_hover.jpg",
        gallery: [
            "images/products/slj014.jpg",
            "images/products/slj014_hover.jpg",
            "images/products/slj014_detail.jpg"
        ],
        description: "Three-strand delicate combination of cultured faux pearls and faceted gold filigree beads.",
        finish: "Anti-tarnish 1-Gram Gold Polish",
        material: "High Lustre Glass Pearls and Gold Filigree Spheres",
        weight: "16 grams",
        size: "Length: 20 inches",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.7,
        reviewsCount: 19
    },
    {
        id: "SLJ015",
        name: "Peacock Matt Finish Bridal Vanki (Armlet)",
        category: "Bridal Sets",
        style: "Temple",
        occasion: "Bridal",
        collection: "Bridal",
        price: 2499,
        originalPrice: 3199,
        image: "images/products/slj015.jpg",
        hoverImage: "images/products/slj015_hover.jpg",
        gallery: [
            "images/products/slj015.jpg",
            "images/products/slj015_hover.jpg",
            "images/products/slj015_detail.jpg"
        ],
        description: "V-shaped traditional bridal armlet with detailed dancing peacock motif and red ruby doublet setting.",
        finish: "Matte Antique Micro Gold Plating",
        material: "Pliable Copper Alloy for custom arm fit",
        weight: "32 grams",
        size: "Adjustable back chain fit",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.9,
        reviewsCount: 21
    },
    {
        id: "SLJ016",
        name: "Classic Sleek CZ Tennis Bracelet",
        category: "Bracelets",
        style: "Contemporary",
        occasion: "Party",
        collection: "New Arrivals",
        price: 1599,
        originalPrice: 1999,
        image: "images/products/slj016.jpg",
        hoverImage: "images/products/slj016_hover.jpg",
        gallery: [
            "images/products/slj016.jpg",
            "images/products/slj016_hover.jpg",
            "images/products/slj016_detail.jpg"
        ],
        description: "Single row diamond-faceted round zircon stones set in micro-prongs with a box clasp safety lock.",
        finish: "Champagne 18k Tone Plating",
        material: "5A Grade Cubic Zirconia on Brass",
        weight: "9.5 grams",
        size: "Length: 7.2 inches with fold-over clasp",
        featured: false,
        newArrival: true,
        trending: true,
        rating: 4.8,
        reviewsCount: 34
    },
    {
        id: "SLJ017",
        name: "Temple Nakshi Lakshmi Stud Earrings",
        category: "Earrings",
        style: "Temple",
        occasion: "Daily",
        collection: "Signature",
        price: 999,
        originalPrice: 1299,
        image: "images/products/slj017.jpg",
        hoverImage: "images/products/slj017_hover.jpg",
        gallery: [
            "images/products/slj017.jpg",
            "images/products/slj017_hover.jpg",
            "images/products/slj017_detail.jpg"
        ],
        description: "Compact Nakshi-worked coin studs depicting seated Lakshmi surrounded by beaded gold rim.",
        finish: "Dull Antique Matte Gold",
        material: "Brass Cast with South Indian screw/push back",
        weight: "6.8 grams pair",
        size: "Diameter: 1.8 cm",
        featured: false,
        newArrival: false,
        trending: true,
        rating: 4.9,
        reviewsCount: 46
    },
    {
        id: "SLJ018",
        name: "Four-Piece Everyday Floral Daily Bangles",
        category: "Bangles",
        style: "Lightweight",
        occasion: "Daily",
        collection: "Signature",
        price: 1799,
        originalPrice: 2299,
        image: "images/products/slj018.jpg",
        hoverImage: "images/products/slj018_hover.jpg",
        gallery: [
            "images/products/slj018.jpg",
            "images/products/slj018_hover.jpg",
            "images/products/slj018_detail.jpg"
        ],
        description: "Set of 4 slender bangles with laser diamond-cut floral patterns that shimmer in natural light.",
        finish: "Long-lasting 1-Gram Daily Gold Dip",
        material: "Lightweight Brass Core",
        weight: "26 grams (Set of 4)",
        size: "Available in 2.4, 2.6, 2.8",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.7,
        reviewsCount: 52
    },
    {
        id: "SLJ019",
        name: "Ganesha Floral Carved Statement Ring",
        category: "Rings",
        style: "Temple",
        occasion: "Festive",
        collection: "Signature",
        price: 949,
        originalPrice: 1249,
        image: "images/products/slj019.jpg",
        hoverImage: "images/products/slj019_hover.jpg",
        gallery: [
            "images/products/slj019.jpg",
            "images/products/slj019_hover.jpg",
            "images/products/slj019_detail.jpg"
        ],
        description: "Spiritual Lord Ganesha motif carved inside an antique floral halo frame, popular for festive poojas.",
        finish: "Antique Temple Polish",
        material: "Brass Base with Ruby CZ Accents",
        weight: "5.8 grams",
        size: "Adjustable Ring Base",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 5.0,
        reviewsCount: 31
    },
    {
        id: "SLJ020",
        name: "South Sea Pearl Drop Locket Pendant",
        category: "Pendants",
        style: "Antique",
        occasion: "Gifting",
        collection: "Signature",
        price: 1399,
        originalPrice: 1799,
        image: "images/products/slj020.jpg",
        hoverImage: "images/products/slj020_hover.jpg",
        gallery: [
            "images/products/slj020.jpg",
            "images/products/slj020_hover.jpg",
            "images/products/slj020_detail.jpg"
        ],
        description: "Ornate Victorian styled floral locket holding a lustrous teardrop pearl hanging, ideal for gifting.",
        finish: "Heritage Two-Tone Gold Finish",
        material: "Kundan and Shell Pearl on Copper",
        weight: "11.5 grams",
        size: "Pendant Length: 2 inches",
        featured: false,
        newArrival: true,
        trending: false,
        rating: 4.8,
        reviewsCount: 22
    },
    {
        id: "SLJ021",
        name: "Royal Rajwadi Matha Patti (Bridal Headband)",
        category: "Bridal Sets",
        style: "Traditional",
        occasion: "Bridal",
        collection: "Bridal",
        price: 2899,
        originalPrice: 3699,
        image: "images/products/slj021.jpg",
        hoverImage: "images/products/slj021_hover.jpg",
        gallery: [
            "images/products/slj021.jpg",
            "images/products/slj021_hover.jpg",
            "images/products/slj021_detail.jpg"
        ],
        description: "Dual-layer bridal forehead ornament with delicate pearl chains and crescent center maang tikka.",
        finish: "Traditional Kundan Matte Gold",
        material: "Kundan Glass Stones, Micro Faux Pearls",
        weight: "34 grams",
        size: "Adjustable pin hooks",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.9,
        reviewsCount: 27
    },
    {
        id: "SLJ022",
        name: "Geometric Modern Link Chain",
        category: "Chains",
        style: "Modern",
        occasion: "Daily",
        collection: "New Arrivals",
        price: 999,
        originalPrice: 1299,
        image: "images/products/slj022.jpg",
        hoverImage: "images/products/slj022_hover.jpg",
        gallery: [
            "images/products/slj022.jpg",
            "images/products/slj022_hover.jpg",
            "images/products/slj022_detail.jpg"
        ],
        description: "Contemporary interlocking oval links with alternating matte and high-polished segments.",
        finish: "Durable Everyday Micro Finish",
        material: "Lightweight High Density Brass",
        weight: "12 grams",
        size: "Length: 22 inches",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.6,
        reviewsCount: 18
    },
    {
        id: "SLJ023",
        name: "Kasu Gold Plated Daily Wear Kada",
        category: "Bracelets",
        style: "Traditional",
        occasion: "Daily",
        collection: "Signature",
        price: 1399,
        originalPrice: 1799,
        image: "images/products/slj023.jpg",
        hoverImage: "images/products/slj023_hover.jpg",
        gallery: [
            "images/products/slj023.jpg",
            "images/products/slj023_hover.jpg",
            "images/products/slj023_detail.jpg"
        ],
        description: "Flexible cuff bracelet lined with tiny stamped Lakshmi Kasu coins and side spring lock mechanism.",
        finish: "Micro Gold Plating",
        material: "Copper-Brass with Spring Lock",
        weight: "18 grams",
        size: "Fits wrist sizes 2.2 to 2.6",
        featured: false,
        newArrival: false,
        trending: true,
        rating: 4.8,
        reviewsCount: 37
    },
    {
        id: "SLJ024",
        name: "Emerald Green Teardrop Party Choker",
        category: "Chokers",
        style: "Contemporary",
        occasion: "Party",
        collection: "Trending",
        price: 2999,
        originalPrice: 3799,
        image: "images/products/slj024.jpg",
        hoverImage: "images/products/slj024_hover.jpg",
        gallery: [
            "images/products/slj024.jpg",
            "images/products/slj024_hover.jpg",
            "images/products/slj024_detail.jpg"
        ],
        description: "Modern cocktail choker encrusted with faceted emerald doublet stones and clear baguette diamonds.",
        finish: "Rhodium & Yellow Gold Dual Tone",
        material: "Hydro Emeralds and Diamond CZ",
        weight: "36 grams",
        size: "Adjustable dori clasp",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 5.0,
        reviewsCount: 41
    },
    {
        id: "SLJ025",
        name: "Layered Jhumka Ear-Chains (Mattal)",
        category: "Jhumkas",
        style: "Traditional",
        occasion: "Wedding",
        collection: "Bridal",
        price: 2199,
        originalPrice: 2799,
        image: "images/products/slj025.jpg",
        hoverImage: "images/products/slj025_hover.jpg",
        gallery: [
            "images/products/slj025.jpg",
            "images/products/slj025_hover.jpg",
            "images/products/slj025_detail.jpg"
        ],
        description: "Traditional two-tier grand jhumkas with connecting pearl hair chains (Champaswaralu/Mattal) for brides.",
        finish: "Matte Temple Gold",
        material: "Brass Base with Hand-linked Pearl Chains",
        weight: "30 grams pair",
        size: "Jhumka: 3.2 inches, Hair chain: 5.5 inches",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.9,
        reviewsCount: 29
    },
    {
        id: "SLJ026",
        name: "Royal Elephant Nakshi Kada (Single)",
        category: "Bangles",
        style: "Temple",
        occasion: "Wedding",
        collection: "Signature",
        price: 2699,
        originalPrice: 3499,
        image: "images/products/slj026.jpg",
        hoverImage: "images/products/slj026_hover.jpg",
        gallery: [
            "images/products/slj026.jpg",
            "images/products/slj026_hover.jpg",
            "images/products/slj026_detail.jpg"
        ],
        description: "Statement heavy-look Kada featuring facing royal elephants with floral carvings and ruby eyes.",
        finish: "Antique Temple Polish",
        material: "Die-cast Brass with Ruby Glass Beads",
        weight: "42 grams",
        size: "2.6 with side hinge & screw",
        featured: false,
        newArrival: true,
        trending: false,
        rating: 4.8,
        reviewsCount: 23
    },
    {
        id: "SLJ027",
        name: "Minimalist Infinity Knot CZ Ring",
        category: "Rings",
        style: "Modern",
        occasion: "Gifting",
        collection: "New Arrivals",
        price: 699,
        originalPrice: 899,
        image: "images/products/slj027.jpg",
        hoverImage: "images/products/slj027_hover.jpg",
        gallery: [
            "images/products/slj027.jpg",
            "images/products/slj027_hover.jpg",
            "images/products/slj027_detail.jpg"
        ],
        description: "Graceful infinity symbol intertwined with delicate micro CZ stones in glossy 18k tone.",
        finish: "High-Shine Gloss Finish",
        material: "Anti-tarnish Copper Alloy",
        weight: "3.1 grams",
        size: "Adjustable 12-18",
        featured: false,
        newArrival: false,
        trending: true,
        rating: 4.7,
        reviewsCount: 49
    },
    {
        id: "SLJ028",
        name: "Traditional Peacock Bugadi / Ear Cuff",
        category: "Earrings",
        style: "Traditional",
        occasion: "Festive",
        collection: "Signature",
        price: 649,
        originalPrice: 849,
        image: "images/products/slj028.jpg",
        hoverImage: "images/products/slj028_hover.jpg",
        gallery: [
            "images/products/slj028.jpg",
            "images/products/slj028_hover.jpg",
            "images/products/slj028_detail.jpg"
        ],
        description: "Traditional Telugu upper-ear helix clip with pearl drops and enamel pink stone.",
        finish: "Micro Antique Polish",
        material: "Lightweight Brass with Clip Pin",
        weight: "4 grams pair",
        size: "Length: 1.5 cm",
        featured: false,
        newArrival: false,
        trending: false,
        rating: 4.6,
        reviewsCount: 16
    },
    {
        id: "SLJ029",
        name: "Kalyani Temple Short Choker Set",
        category: "Chokers",
        style: "Temple",
        occasion: "Wedding",
        collection: "Bridal",
        price: 4199,
        originalPrice: 5399,
        image: "images/products/slj029.jpg",
        hoverImage: "images/products/slj029_hover.jpg",
        gallery: [
            "images/products/slj029.jpg",
            "images/products/slj029_hover.jpg",
            "images/products/slj029_detail.jpg"
        ],
        description: "Divine floral and goddess engravings bordered with high quality emerald drops, includes matching earrings.",
        finish: "Micro-Plated Matte Antique",
        material: "Brass Casting with Hydro Gemstones",
        weight: "52 grams",
        size: "Choker + Earrings set",
        featured: true,
        newArrival: false,
        trending: true,
        rating: 4.9,
        reviewsCount: 43
    },
    {
        id: "SLJ030",
        name: "Maharani Multi-layer Kundan Bridal Rani Haar",
        category: "Harams",
        style: "Antique",
        occasion: "Bridal",
        collection: "Bridal",
        price: 5999,
        originalPrice: 7799,
        image: "images/products/slj030.jpg",
        hoverImage: "images/products/slj030_hover.jpg",
        gallery: [
            "images/products/slj030.jpg",
            "images/products/slj030_hover.jpg",
            "images/products/slj030_detail.jpg"
        ],
        description: "Showstopper seven-layer bridal Rani Haar crafted with uncut glass polki, ruby cabochons, and pearl bunches.",
        finish: "Antique Victorian Polish",
        material: "Kundan, Green Onyx Beads, Faux Pearls",
        weight: "92 grams",
        size: "Length: 30 inches with side clips",
        featured: true,
        newArrival: true,
        trending: true,
        rating: 5.0,
        reviewsCount: 62
    },
    {
        id: "SLJ031",
        name: "Vintage Filigree Flower Pendant Locket",
        category: "Pendants",
        style: "Antique",
        occasion: "Gifting",
        collection: "Signature",
        price: 1199,
        originalPrice: 1499,
        image: "images/products/slj031.jpg",
        hoverImage: "images/products/slj031_hover.jpg",
        gallery: [
            "images/products/slj031.jpg",
            "images/products/slj031_hover.jpg",
            "images/products/slj031_detail.jpg"
        ],
        description: "Opening photo locket with royal floral jaali filigree carving, suspended on gold link chain.",
        finish: "Antique Micro Gold Polish",
        material: "Solid Brass with Photo Insert Slots",
        weight: "14 grams",
        size: "Pendant: 3.5 cm x 2.8 cm",
        featured: false,
        newArrival: true,
        trending: false,
        rating: 4.8,
        reviewsCount: 24
    },
    {
        id: "SLJ032",
        name: "Delicate Evil Eye Protection Charm Bracelet",
        category: "Bracelets",
        style: "Modern",
        occasion: "Daily",
        collection: "New Arrivals",
        price: 849,
        originalPrice: 1099,
        image: "images/products/slj032.jpg",
        hoverImage: "images/products/slj032_hover.jpg",
        gallery: [
            "images/products/slj032.jpg",
            "images/products/slj032_hover.jpg",
            "images/products/slj032_detail.jpg"
        ],
        description: "Sleek blue enamel evil eye charm surrounded by sparkling micro CZ stones on a fine adjustable chain.",
        finish: "18k Rose-Gold & Yellow Gold Finish",
        material: "Tarnish-Resistant Alloy & Cubic Zirconia",
        weight: "5.2 grams",
        size: "Adjustable 6.5 to 8.5 inches",
        featured: false,
        newArrival: true,
        trending: true,
        rating: 4.9,
        reviewsCount: 47
    }
];

// Helper functions for catalog queries
function getAllProducts() {
    return PRODUCTS;
}

function getProductById(id) {
    if (!id) return null;
    return PRODUCTS.find(p => p.id.toUpperCase() === id.toUpperCase()) || null;
}

function getFeaturedProducts(limit = 8) {
    return PRODUCTS.filter(p => p.featured).slice(0, limit);
}

function getNewArrivals(limit = 8) {
    return PRODUCTS.filter(p => p.newArrival).slice(0, limit);
}

function getTrendingProducts(limit = 8) {
    return PRODUCTS.filter(p => p.trending).slice(0, limit);
}

function getBridalProducts(limit = 12) {
    return PRODUCTS.filter(p => p.category === "Bridal Sets" || p.occasion === "Bridal" || p.collection === "Bridal" || p.occasion === "Wedding").slice(0, limit);
}

function getCategories() {
    return [...new Set(PRODUCTS.map(p => p.category))];
}

function getStyles() {
    return [...new Set(PRODUCTS.map(p => p.style))];
}

function getOccasions() {
    return [...new Set(PRODUCTS.map(p => p.occasion))];
}
